-- MySQL Script generated by MySQL Workbench
-- 10/08/15 23:26:14
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema university_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema university_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `university_db` DEFAULT CHARACTER SET utf8 ;
USE `university_db` ;

-- -----------------------------------------------------
-- Table `university_db`.`faculties`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `university_db`.`faculties` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(50) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `university_db`.`departments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `university_db`.`departments` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(50) NOT NULL COMMENT '',
  `faculty_id` INT(11) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_departments_faculties_idx` (`faculty_id` ASC)  COMMENT '',
  CONSTRAINT `fk_departments_faculties`
    FOREIGN KEY (`faculty_id`)
    REFERENCES `university_db`.`faculties` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `university_db`.`professors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `university_db`.`professors` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `first_name` VARCHAR(45) NOT NULL COMMENT '',
  `last_name` VARCHAR(45) NOT NULL COMMENT '',
  `department_id` INT(11) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_professors_departments1_idx` (`department_id` ASC)  COMMENT '',
  CONSTRAINT `fk_professors_departments1`
    FOREIGN KEY (`department_id`)
    REFERENCES `university_db`.`departments` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `university_db`.`courses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `university_db`.`courses` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(50) NOT NULL COMMENT '',
  `department_id` INT(11) NOT NULL COMMENT '',
  `professor_id` INT(11) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_courses_departments1_idx` (`department_id` ASC)  COMMENT '',
  INDEX `fk_courses_professors1_idx` (`professor_id` ASC)  COMMENT '',
  CONSTRAINT `fk_courses_departments1`
    FOREIGN KEY (`department_id`)
    REFERENCES `university_db`.`departments` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_courses_professors1`
    FOREIGN KEY (`professor_id`)
    REFERENCES `university_db`.`professors` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `university_db`.`titles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `university_db`.`titles` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(50) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `university_db`.`professor_titles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `university_db`.`professor_titles` (
  `professor_id` INT(11) NOT NULL COMMENT '',
  `title_id` INT(11) NOT NULL COMMENT '',
  PRIMARY KEY (`professor_id`, `title_id`)  COMMENT '',
  INDEX `fk_professor_titles_professors1_idx` (`professor_id` ASC)  COMMENT '',
  INDEX `fk_professor_titles_titles1_idx` (`title_id` ASC)  COMMENT '',
  CONSTRAINT `fk_professor_titles_professors1`
    FOREIGN KEY (`professor_id`)
    REFERENCES `university_db`.`professors` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_professor_titles_titles1`
    FOREIGN KEY (`title_id`)
    REFERENCES `university_db`.`titles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `university_db`.`students`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `university_db`.`students` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `first_name` VARCHAR(50) NOT NULL COMMENT '',
  `last_name` VARCHAR(50) NOT NULL COMMENT '',
  `faculty_id` INT(11) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_students_faculties1_idx` (`faculty_id` ASC)  COMMENT '',
  CONSTRAINT `fk_students_faculties1`
    FOREIGN KEY (`faculty_id`)
    REFERENCES `university_db`.`faculties` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `university_db`.`student_courses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `university_db`.`student_courses` (
  `course_id` INT(11) NOT NULL COMMENT '',
  `student_id` INT(11) NOT NULL COMMENT '',
  PRIMARY KEY (`course_id`, `student_id`)  COMMENT '',
  INDEX `fk_student_courses_courses1_idx` (`course_id` ASC)  COMMENT '',
  INDEX `fk_student_courses_students1_idx` (`student_id` ASC)  COMMENT '',
  CONSTRAINT `fk_student_courses_courses1`
    FOREIGN KEY (`course_id`)
    REFERENCES `university_db`.`courses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_student_courses_students1`
    FOREIGN KEY (`student_id`)
    REFERENCES `university_db`.`students` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
