//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DayOfTheWeekConsoleClient.DayOfTheWeekServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DayOfTheWeekServiceReference.IDayOfTheWeekService")]
    public interface IDayOfTheWeekService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDayOfTheWeekService/DayOfWeekBulgarian", ReplyAction="http://tempuri.org/IDayOfTheWeekService/DayOfWeekBulgarianResponse")]
        string DayOfWeekBulgarian(System.DateTime date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDayOfTheWeekService/DayOfWeekBulgarian", ReplyAction="http://tempuri.org/IDayOfTheWeekService/DayOfWeekBulgarianResponse")]
        System.Threading.Tasks.Task<string> DayOfWeekBulgarianAsync(System.DateTime date);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDayOfTheWeekServiceChannel : DayOfTheWeekConsoleClient.DayOfTheWeekServiceReference.IDayOfTheWeekService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DayOfTheWeekServiceClient : System.ServiceModel.ClientBase<DayOfTheWeekConsoleClient.DayOfTheWeekServiceReference.IDayOfTheWeekService>, DayOfTheWeekConsoleClient.DayOfTheWeekServiceReference.IDayOfTheWeekService {
        
        public DayOfTheWeekServiceClient() {
        }
        
        public DayOfTheWeekServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DayOfTheWeekServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DayOfTheWeekServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DayOfTheWeekServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string DayOfWeekBulgarian(System.DateTime date) {
            return base.Channel.DayOfWeekBulgarian(date);
        }
        
        public System.Threading.Tasks.Task<string> DayOfWeekBulgarianAsync(System.DateTime date) {
            return base.Channel.DayOfWeekBulgarianAsync(date);
        }
    }
}
