//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StringServiceConsoleClient.AppearancesCounterServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AppearancesCounterServiceReference.IAppearancesCounter")]
    public interface IAppearancesCounter {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAppearancesCounter/CountStringAppearances", ReplyAction="http://tempuri.org/IAppearancesCounter/CountStringAppearancesResponse")]
        int CountStringAppearances(string occuringString, string containingString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAppearancesCounter/CountStringAppearances", ReplyAction="http://tempuri.org/IAppearancesCounter/CountStringAppearancesResponse")]
        System.Threading.Tasks.Task<int> CountStringAppearancesAsync(string occuringString, string containingString);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAppearancesCounterChannel : StringServiceConsoleClient.AppearancesCounterServiceReference.IAppearancesCounter, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AppearancesCounterClient : System.ServiceModel.ClientBase<StringServiceConsoleClient.AppearancesCounterServiceReference.IAppearancesCounter>, StringServiceConsoleClient.AppearancesCounterServiceReference.IAppearancesCounter {
        
        public AppearancesCounterClient() {
        }
        
        public AppearancesCounterClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AppearancesCounterClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AppearancesCounterClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AppearancesCounterClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int CountStringAppearances(string occuringString, string containingString) {
            return base.Channel.CountStringAppearances(occuringString, containingString);
        }
        
        public System.Threading.Tasks.Task<int> CountStringAppearancesAsync(string occuringString, string containingString) {
            return base.Channel.CountStringAppearancesAsync(occuringString, containingString);
        }
    }
}
